---
title: "Proyecto 1: el microbioma del pulque"
author: "Patricia Bustos, Celso Cortés, Antonio Ovalle, José Ovando, Tobias Portillo, Armando Ocampo"
institute: "CDSD 2022"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      

---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```
---

# Flujo de trabajo

a) MaxBin

b) MetaBat

c) DASTool

d) Extracción de Bins

---

# MaxBin

Generación de enlaces simbólicos

```{r MAX, eval=FALSE}
 mkdir -p 01.Metabat/{data,results}
 cd 01.Metabat/
 ln -s /home/diana/samples/pulque/data/pulque.fasta data/  
 ln -s /home/diana/samples/pulque/data/pulque_sorted.bam  data/ 
```

Activación de ambiente

```{r max1, eval=FALSE}
conda activate maxbin_env
```

Cálculo de bins

```{r max2, eval=FALSE}
run_MaxBin.pl -contig data/pulque.fasta -out results/maxbin -abund data/pulque-depth.txt -max_iteration 2
```

---

# MetaBat

```{r meta, eval=FALSE}
mkdir -p 02.Metabat/{data,results}
cd 02.Metabat/
ln -s /home/diana/samples/pulque/data/pulque.fasta data/  
ln -s /home/diana/samples/pulque/data/pulque_sorted.bam  data/ 
```

Activamos el ambiente
```{r meta2, eval=FALSE}
conda activate metabat_env
```

Ensamble y archivos de profundidad

```{r meta3, eval=FALSE}
jgi_summarize_bam_contig_depths --outputDepth data/pulque-depth.txt data/pulque_sorted.bam

metabat -i data/pulque.fasta -a data/pulque-depth.txt -o results/bins -t 4 --minCVSum 0 --saveCls -d -v --minCV 0.1 -m 2000
```

---
# DASTool

Refinamiento


Preparar datos de entrada

```{r das, eval=FALSE}

Fasta_to_Scaffolds2Bin.sh -i /home/user*/01.Metabat -e fa > htn.scaffolds2bin.tsv
```


```{r das2, eval=FALSE}
PATH=/home/programs:$PATH

cd /home/programs/DAS_Tool-1.1.2

R CMD INSTALL package/DASTool_1.1.2.tar.gz

/home/programs/DAS_Tool-1.1.2/DAS_Tool -i pulque_maxbin.contigs2bin.tsv,pulque_metabat.scaffolds2bin.tsv -l maxbin,metabat -c data/pulque.fasta -o results/pulque_bins --debug -t 4  --search_engine diamond --write_bins 1 
```


---

# Extracción de Bins

```{r che, eval=FALSE}
mkdir 03.CheckM

cd 03.CheckM/

```

Activamos el ambiente

```{r che2, eval=FALSE}
conda activate checkm_env
```

```{r che3, eval=FALSE}
checkm  lineage_wf -t 4 -x fa /home/user/04.DAS_tool/results/pulque_bins_DASTool_bins DAStools-log_htn  -f CheckM-DAS_Tool_bins.txt

sed -e '1,3d' CheckM-DAS_Tool_bins.txt | sed -e '37d' >CheckM-DAS_Tool_bins_mod.txt
```



